<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Kugan-PC" ignored="0" name="Test1" tests="1" failures="1" timestamp="01 Aug 2020 12:48:44 GMT" time="55.821" errors="0">
  <testcase name="vali_Text" time="7.191" classname="completeFramework.ValidateText">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at completeFramework.ValidateText.vali_Text(ValidateText.java:33)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- vali_Text -->
</testsuite> <!-- Test1 -->
